name: Keep Upstash Alive

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" 

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Redis Usage with SET & GET
        run: |
          curl -X POST "${{ secrets.UPSTASH_REDIS_REST_URL }}/set/keepalive" \
            -H "Authorization: Bearer ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}" \
            -d "\"true\""
          
          curl -X POST "${{ secrets.UPSTASH_REDIS_REST_URL }}/get/keepalive" \
            -H "Authorization: Bearer ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}"
