name: Keep Upstash Alive

on:
  schedule:
    - cron: "0 0 * * *" 

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Upstash Redis PING
        run: |
          curl -u "default:${{ secrets.UPSTASH_REDIS_REST_TOKEN }}" \
          "${{ secrets.UPSTASH_REDIS_REST_URL }}/PING"
