name: Keep Upstash Alive

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"  

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Redis Usage with SET & GET
        run: |
          curl -s -u "default:${{ secrets.UPSTASH_REDIS_REST_TOKEN }}" \
            "${{ secrets.UPSTASH_REDIS_REST_URL }}/SET/keepalive/true"
          
          curl -s -u "default:${{ secrets.UPSTASH_REDIS_REST_TOKEN }}" \
            "${{ secrets.UPSTASH_REDIS_REST_URL }}/GET/keepalive"
